export { default as PaginaInicio } from './pagina-inicio/PaginaInicio';
export { default as IniciarSesion } from './iniciar-sesion/IniciarSesion';
export { default as PaginaPreMatricula } from './pre-matricula/PreMatricula';
export { default as PaginaFormularioFut } from './formulario-fut/FormularioFut';
export { default as PaginaCargarDocumentos } from './gestionar-documentos/cargar-documentos/CargarDocumentos';
export { default as PaginaEliminarDocumentos } from './gestionar-documentos/eliminar-documentos/EliminarDocumentos';
export { default as AsignarDocente } from './asignar-docente/AsignarDocente';
export { default as PaginaRegistrarse } from './pagina-registrar/PaginaRegistrar';
export { default as PaginaPerfil } from './pagina-perfil/PaginaPerfil';